"""
QA context builder — assembles three context sources for contract Q&A:

  A. Contract clauses    (contract_clauses, scoped to this review)
  B. Review results      (contract_review_cards + contract_evidence + revision_accepts)
  C. Live law retrieval  (hybrid_search on civil_code_hybrid)

Hard rules implemented here:
  - Scope guard: every SQL query is filtered by contract_id — data from other
    contracts never enters the context (data-level isolation).
  - Grounded citations: the citation list is generated by the backend from
    retrieval results, never from LLM self-reports.
"""
from __future__ import annotations

import asyncio
import logging
import re
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from backend.agents.contract_review.rag_retriever import cn_to_int
from backend.core.context_manager import TOKEN_BUDGET, estimate_tokens
from backend.core.rag import get_kb_client

logger = logging.getLogger(__name__)

LAW_COLLECTION = "civil_code_hybrid"
QA_TOKEN_BUDGET = TOKEN_BUDGET  # 8000, shared estimate basis with review pipeline
MAX_LAW_HITS = 3
MAX_EVIDENCE_PER_CLAUSE = 2
LAW_RETRIEVE_THRESHOLD = 0.30  # calibrated reranker threshold (T5)
LAW_CONFIDENT_THRESHOLD = 0.70  # 二次路由：top≥此值视为强命中(CONFIDENT)，否则 WEAK；初值待 20 题黄金集标定

_LEVEL_RANK = {"高": 3, "中": 2, "低": 1, "无": 0}


# ── Source loading (scope guard: all queries filtered by contract_id) ──────

async def fetch_contract_sources(db: Any, contract_id: int) -> dict[str, Any]:
    """Load contract-scoped sources from PG. Returns {} if contract missing."""
    review = await db.fetchrow(
        "SELECT id, user_id, original_filename, contract_type, status "
        "FROM contract_reviews WHERE id = $1",
        contract_id,
    )
    if not review:
        return {}

    clauses = await db.fetch(
        "SELECT clause_id, seq_no, type, title, content "
        "FROM contract_clauses WHERE review_id = $1 ORDER BY seq_no",
        contract_id,
    )
    cards = await db.fetch(
        "SELECT clause_id, dimension, score, level, suggestion, risk_type "
        "FROM contract_review_cards WHERE review_id = $1 ORDER BY score DESC",
        contract_id,
    )
    evidence = await db.fetch(
        "SELECT clause_id, source_id, source_collection, quote, confidence "
        "FROM contract_evidence WHERE review_id = $1 "
        "ORDER BY confidence DESC NULLS LAST",
        contract_id,
    )
    revisions = await db.fetch(
        "SELECT clause_id, before_text, after_text, status "
        "FROM revision_accepts WHERE review_id = $1",
        contract_id,
    )
    return {
        "review": dict(review),
        "clauses": [dict(c) for c in clauses],
        "cards": [dict(c) for c in cards],
        "evidence": [dict(e) for e in evidence],
        "revisions": [dict(r) for r in revisions],
    }


# ── Multi-query split (T2, 2026-08-07) ──────────────────────
# Compound questions ("定金和违约金能并用吗？比例上限又是多少？") push two
# intents into one query and retrieval favours one side. Rule-based split:
# punctuation ？?；; plus additive connectives; ≤3 fragments, each ≥6 chars.
# Unsplittable questions return themselves, so single-intent questions keep
# exactly the pre-T2 behavior.

_SPLIT_PUNCT_RE = re.compile(r"[？?；;]")
_SPLIT_CONN_RE = re.compile(r"另外|还有|并且|以及|此外")
_FRAG_TRIM_RE = re.compile(r"^[，,、。.\s]+|[，,、。.\s]+$")
_EDGE_SPLIT_PUNCT_RE = re.compile(r"^[？?；;\s]+|[？?；;\s]+$")
MIN_SUB_QUERY_CHARS = 6
MAX_SUB_QUERIES = 3


def split_sub_queries(question: str) -> list[str]:
    """Split a compound question into ≤3 independent sub-questions.

    Single-intent guard: when the split leaves exactly one fragment that is
    just the original minus edge punctuation (i.e. nothing was really split
    off), the ORIGINAL question is returned verbatim. Single-intent questions
    must keep exactly the pre-T2 retrieval behavior — dropping a trailing '？'
    alone was enough to flip a knife-edge rerank (eval C1: 第580条@0.4515 vs
    第593条@0.4477 with the mark; the order inverts without it).
    """
    q = (question or "").strip()
    if not q:
        return []
    parts: list[str] = []
    for piece in _SPLIT_PUNCT_RE.split(q):
        for frag in _SPLIT_CONN_RE.split(piece):
            frag = _FRAG_TRIM_RE.sub("", frag)
            if len(frag) >= MIN_SUB_QUERY_CHARS:
                parts.append(frag)
    if not parts:  # nothing splittable / everything too short → keep as-is
        return [q]
    out: list[str] = []
    seen: set[str] = set()
    for p in parts:
        if p in seen:
            continue
        seen.add(p)
        out.append(p)
        if len(out) >= MAX_SUB_QUERIES:
            break
    if len(out) == 1 and out[0] == _EDGE_SPLIT_PUNCT_RE.sub("", q):
        return [q]
    return out


# ── HyDE low-score retry (T3, 2026-08-08) ──────────────────────
# When the first-round merged top score is weak, the QA LLM writes a
# hypothetical civil-code article answering the colloquial question, and that
# hypothesis is searched once. Rationale: colloquial phrasing ("仓库被雷劈了
# 着火…我还要赔吗") shares almost no vocabulary with statute text (第590条
# 不可抗力), so dense+sparse retrieval misses; a statute-style hypothesis
# bridges the lexical gap (2026-08-08 probe: the C1/C3/C4 hypotheses surfaced
# the expected articles at rerank 0.93–0.99).
#
# Threshold note: the plan's default was 0.30, but after the T1 hard cutoff
# every returned hit is already ≥0.30, so "top < 0.30" collapses to "zero
# hits" and HyDE would never fire. Baseline tops split into weak colloquials
# ≤0.79 (C1=0.72, C3=0.79, C4=0.54) vs strong hits ≥0.91 (all L/M questions
# and C2), so the retry threshold sits in the gap at 0.80.

HYDE_ENABLED = True
HYDE_RETRY_THRESHOLD = 0.80
HYDE_MAX_TOKENS = 300
HYDE_TIMEOUT_SECONDS = 20.0
# Plan allows ≤0.2; 0.0 keeps the hypothesis reproducible — the same question
# must not cite different articles on different runs (sampling at 0.2 was
# observed to flip C1's hypothesis between 违约责任 and 解除合同 framings).
HYDE_TEMPERATURE = 0.0

# Built by plain concatenation — no .format() placeholders to mismatch.
_HYDE_SYSTEM_PROMPT = (
    "你是法律检索助手。用户会用口语描述一个合同纠纷问题。"
    "请写出《中华人民共和国民法典》中最可能直接回答该问题的一条条文的假设原文，"
    "约100字，采用法条书面语风格。"
    "要求：只输出条文内容本身；不要输出条文序号；不要任何解释。"
)


def _get_qa_llm():
    """QA-dedicated LLM for HyDE (Q-1: never the review instance in core.llm).

    Lazy import: qa_service imports this module at import time, so a
    module-level import here would be circular.
    """
    from backend.agents.contract_qa.qa_service import _build_qa_llm

    return _build_qa_llm(max_tokens=HYDE_MAX_TOKENS, temperature=HYDE_TEMPERATURE)


async def _generate_hyde_hypothesis(question: str) -> str:
    """Best-effort hypothetical statute text. Any failure returns '' (no retry)."""
    try:
        llm = _get_qa_llm()
        messages = [
            SystemMessage(content=_HYDE_SYSTEM_PROMPT),
            HumanMessage(content=question),
        ]
        resp = await asyncio.wait_for(
            llm.ainvoke(messages), timeout=HYDE_TIMEOUT_SECONDS
        )
        content = getattr(resp, "content", "") or ""
        return content.strip() if isinstance(content, str) else str(content).strip()
    except Exception:
        logger.exception("HyDE hypothesis generation failed; keeping first-round hits")
        return ""


async def _search_law_pools(queries: list[str]) -> list[list[dict[str, Any]]]:
    """One hybrid_search per query, in parallel; a failing path degrades to []."""

    async def _search_one(query: str) -> list[dict[str, Any]]:
        try:
            kb = get_kb_client()
            hits = await kb.hybrid_search(
                query,
                LAW_COLLECTION,
                top_k=10,
                rerank_top_k=MAX_LAW_HITS,
                threshold=LAW_RETRIEVE_THRESHOLD,
            )
            return hits or []
        except Exception:
            logger.exception(
                f"QA law retrieval failed for sub-query {query[:40]!r}, degrading to empty"
            )
            return []

    return list(await asyncio.gather(*[_search_one(q) for q in queries]))


def _select_round_robin(pools: list[list[dict[str, Any]]]) -> list[dict[str, Any]]:
    """T2 selection across sub-query pools (behavior unchanged).

    Round-robin gives each sub-query one slot per turn until the cap is
    filled, instead of pooling everything and sorting by confidence: a global
    sort lets one high-scoring sub-query sweep all the slots and starve the
    others (eval M2: sub-query 1 returned 563/562/565 and pushed out
    sub-query 2's 566@0.83). Dedup by id keeps the max confidence; a
    duplicate does not consume a slot; the T1 hard cutoff is applied per hit;
    a failing sub-query (empty list) degrades only itself.
    """
    by_id: dict[str, dict[str, Any]] = {}
    cursors = [0] * len(pools)
    picked_ids: list[str] = []
    while len(picked_ids) < MAX_LAW_HITS:
        progressed = False
        for i, hits in enumerate(pools):
            if len(picked_ids) >= MAX_LAW_HITS:
                break
            while cursors[i] < len(hits):
                h = hits[cursors[i]]
                cursors[i] += 1
                conf = float(h.get("confidence", 0.0))
                if conf < LAW_RETRIEVE_THRESHOLD:  # T1 hard cutoff
                    continue
                sid = str(h.get("id", ""))
                if not sid:
                    continue
                if sid in by_id:  # duplicate → keep max confidence, no new slot
                    if conf > float(by_id[sid].get("confidence", 0.0)):
                        by_id[sid] = h
                    continue
                by_id[sid] = h
                picked_ids.append(sid)
                progressed = True
                break
        if not progressed:
            break  # every sub-query exhausted or below threshold

    chosen = [by_id[sid] for sid in picked_ids]
    chosen.sort(key=lambda h: float(h.get("confidence", 0.0)), reverse=True)

    merged_best: dict[str, float] = {}
    for hits in pools:
        for h in hits:
            sid = str(h.get("id", ""))
            if sid:
                conf = float(h.get("confidence", 0.0))
                merged_best[sid] = max(merged_best.get(sid, conf), conf)
    dropped = sum(1 for c in merged_best.values() if c < LAW_RETRIEVE_THRESHOLD)
    if dropped:
        logger.info(
            f"QA law cutoff dropped {dropped} sub-threshold hits "
            f"(threshold={LAW_RETRIEVE_THRESHOLD}, sub_queries={len(pools)})"
        )
    return chosen


def _merge_pools_by_confidence(
    pools: list[list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    """T1 cutoff + id-dedupe keeping max confidence across all pools."""
    merged: dict[str, dict[str, Any]] = {}
    for hits in pools:
        for h in hits:
            conf = float(h.get("confidence", 0.0))
            if conf < LAW_RETRIEVE_THRESHOLD:
                continue
            sid = str(h.get("id", ""))
            if not sid:
                continue
            if sid in merged:
                if conf > float(merged[sid].get("confidence", 0.0)):
                    merged[sid] = h
            else:
                merged[sid] = h
    return merged


async def retrieve_law_hits(
    queries: list[str], hyde_question: str | None = None
) -> list[dict[str, Any]]:
    """Live hybrid retrieval for every sub-query, in parallel, merged.

    T2: each sub-query is searched independently (search params unchanged);
    results are merged by source id keeping the highest confidence, then the
    T1 hard cutoff drops sub-threshold hits and the survivors are capped at
    MAX_LAW_HITS via round-robin across sub-queries (cutting before capping
    lets a 4th-place 0.45 hit backfill a slot freed from a 0.10 hit). A
    failing sub-query degrades only itself. The review pipeline does not use
    this function and keeps its own behavior.

    T3 HyDE: when ``hyde_question`` (the RAW user question — never the
    risk_type-enriched query) is given and the first-round top score stays
    below HYDE_RETRY_THRESHOLD, one retry is attempted: the QA LLM writes a
    hypothetical statute and that hypothesis is searched once. The hypothesis
    pool is merged with ALL first-round candidates by confidence (same T1
    cutoff + id dedupe). This deliberately differs from the round-robin used
    across sub-queries: round-robin protects DISTINCT sub-intents from
    starvation, but the hypothesis restates the SAME intent, so its hits
    compete on score. Every HyDE failure (disabled, LLM error/timeout, empty
    hypothesis, empty hypothesis search) degrades to the first-round result,
    which keeps behavior identical to T2 whenever HyDE does not fire.
    """
    queries = [q for q in (queries or []) if q and q.strip()]
    if not queries:
        return []

    pools = await _search_law_pools(queries)
    first_round = _select_round_robin(pools)

    if not (HYDE_ENABLED and hyde_question and hyde_question.strip()):
        return first_round
    top_conf = max(
        (float(h.get("confidence", 0.0)) for h in first_round), default=0.0
    )
    if top_conf >= HYDE_RETRY_THRESHOLD:
        return first_round

    hypothesis = await _generate_hyde_hypothesis(hyde_question.strip())
    if not hypothesis:
        return first_round
    hyde_pools = await _search_law_pools([hypothesis])
    if not hyde_pools or not hyde_pools[0]:
        return first_round

    merged = _merge_pools_by_confidence(pools + hyde_pools)
    chosen = sorted(
        merged.values(), key=lambda h: float(h.get("confidence", 0.0)), reverse=True
    )[:MAX_LAW_HITS]
    logger.info(
        f"QA HyDE retry (contract QA): first-round top={top_conf:.3f} < "
        f"{HYDE_RETRY_THRESHOLD}; question={hyde_question[:40]!r}; "
        f"hypothesis={hypothesis[:60]!r}; "
        f"articles={[h.get('article_no') for h in chosen]}"
    )
    return chosen


def build_citations(law_hits: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Backend-generated citation list (grounded). Never trust LLM self-reports."""
    citations: list[dict[str, Any]] = []
    for i, hit in enumerate(law_hits, start=1):
        citations.append({
            "ref": f"[{i}]",
            "source_id": str(hit.get("id", "")),
            "article_no": hit.get("article_no", ""),
            "chapter": hit.get("chapter", ""),
            "collection": LAW_COLLECTION,
            "score": round(float(hit.get("confidence", 0.0)), 4),
            "quote": (hit.get("content", "") or "")[:200],
        })
    return citations


# ── Confidence re-routing (T7, 二次路由) ──────────────────────
# Post-retrieval decision: weak hits must not be cited with the same
# confidence as strong ones. HyDE retries retrieval when weak (T3); this
# tiering changes the ANSWER strategy when still weak after retry. EMPTY is
# handled upstream via law_empty + NO_LAW_NOTE; WEAK adds a hedge note so the
# LLM softens the claim instead of asserting it as certain.
def classify_law_confidence(law_hits: list[dict[str, Any]]) -> str:
    """Route final law hits to CONFIDENT / WEAK / EMPTY by top confidence."""
    if not law_hits:
        return "EMPTY"
    top = max(float(h.get("confidence", 0.0)) for h in law_hits)
    return "CONFIDENT" if top >= LAW_CONFIDENT_THRESHOLD else "WEAK"


# ── Query rewrite (T6 fix, 2026-08-07) ──────────────────────
# The raw user question often lacks statute-level vocabulary (e.g. it says
# "违约责任有什么高风险" but never the words "违约金"/"定金"), so sparse
# retrieval cannot land on the right articles. We enrich the query with the
# precise risk_type terms already produced by the review cards.

_CLAUSE_REF_RE = re.compile(r"第\s*([0-9一二三四五六七八九十百零]+)\s*条")
MAX_QUERY_TERMS = 4
_LEVEL_ORDER = {"高": 3, "中": 2, "低": 1, "无": 0}


def _referenced_clause_ids(question: str, clauses: list[dict[str, Any]]) -> set[str]:
    """Clause ids the question points at, via '第X条' numbers or title mentions."""
    ids: set[str] = set()
    for m in _CLAUSE_REF_RE.finditer(question):
        token = m.group(1)
        n = int(token) if token.isdigit() else cn_to_int(token)
        if n <= 0:
            continue
        for c in clauses:
            if c.get("seq_no") == n:
                ids.add(c.get("clause_id", ""))
    for c in clauses:
        title = (c.get("title") or "").strip()
        if title and len(title) >= 2 and title in question:
            ids.add(c.get("clause_id", ""))
    return ids


def build_law_query(
    question: str,
    clauses: list[dict[str, Any]],
    cards: list[dict[str, Any]],
) -> str:
    """Enrich the user question with precise legal terms from the review cards.

    Terms come from the referenced clauses when the question points at specific
    clauses; otherwise from the highest-risk cards overall. The original question
    is kept first so semantic matching still sees the user's intent.
    """
    q = (question or "").strip()
    ref_ids = _referenced_clause_ids(q, clauses)
    pool = [c for c in cards if c.get("clause_id") in ref_ids] if ref_ids else cards
    pool = sorted(pool, key=lambda c: _LEVEL_ORDER.get(c.get("level", "无"), 0), reverse=True)

    terms: list[str] = []
    for c in pool:
        rt = (c.get("risk_type") or "").strip()
        if rt and rt not in terms:
            terms.append(rt)
        if len(terms) >= MAX_QUERY_TERMS:
            break

    return " ".join([q] + terms)


# ── Question intent classification (T1, 2026-08-07) ───────
# Four routes: META / CLAUSE / GENERIC / LAW. The meta gate below is the
# META branch; classify_question adds the other three.
#
# Design rule: misrouting a genuine LAW question away from retrieval is far
# worse than letting a non-LAW question go through retrieval (the hard
# cutoff in retrieve_law_hits still prevents false citations there). Every
# non-LAW rule is therefore deliberately narrow, and the default route is LAW.
#
#   META    — greetings / identity / capability (existing gate)
#   CLAUSE  — the answer lives in this contract's own data (clause text,
#             review cards, revision suggestions); no statute lookup needed
#   GENERIC — outside the civil-code KB coverage (labor/social-insurance
#             domains); retrieval there can only fabricate relevance
#   LAW     — needs statute grounding → full retrieval pipeline
#
# NOTE (history): without the META gate, build_law_query injected the
# contract's top risk_type terms into greetings/capability questions (they
# reference no clause, so pool = ALL cards) and retrieval returned unrelated
# statutes with misleadingly high scores — "你可以干什么" landed on
# 第585/588条 at 58%/39%. Non-legal questions must skip retrieval entirely.

_META_MAX_CHARS = 24  # meta questions are short; longer text stays un-gated

_META_PATTERNS = [
    # greetings / thanks / ack / farewell — near-exact match only
    r"^(你好|您好|嗨|哈喽|哈啰|hello|hi|hey|在吗|在不在)$",
    r"^(谢谢|多谢|感谢|辛苦了|好的|明白了|知道了|收到|嗯|ok|okay)$",
    r"^(再见|拜拜|拜|bye)$",
    # identity / self-intro
    r"(你是谁|你叫什么|你是什么助手|你是什么模型|介绍一下你自己|自我介绍)",
    # capability / usage — anchored to 你/您 so real legal questions such as
    # "我可以干什么" / "这份合同能做哪些修改" / "违约金条款有什么用" never match
    r"[你您](可以|能|会)(帮我)?(干|做|回答)(些)?(什么|啥|哪些)",
    r"[你您](有什么用|有什么功能|有哪些功能|都能做什么|都会什么|能提供什么)",
    r"[你您]是(干什么|做什么|干嘛)的",
    r"怎么使用你|你的功能",
]

_META_RE = [re.compile(p) for p in _META_PATTERNS]
_META_STRIP_RE = re.compile(r"[\s\?？!！.。~～，,、:：;；·'\"“”‘’()（）]+")


def is_meta_question(question: str) -> bool:
    """True for greetings / identity / capability / thanks questions.

    Deliberately narrow: every capability pattern is anchored to 你/您 and
    only short text (<= _META_MAX_CHARS after normalization) is considered,
    so genuine legal questions are never gated away from retrieval.
    """
    q = (question or "").strip()
    if not q:
        return True
    norm = _META_STRIP_RE.sub("", q).lower()
    if len(norm) > _META_MAX_CHARS:
        return False
    return any(p.search(norm) for p in _META_RE)


# CLAUSE branch: the answer lives in this contract's own data ──
# R2/R3: questions about the review output itself (review cards / revision
# suggestions already in context answer them).
_REVIEW_SELF_RE = re.compile(r"审查结果|审查发现|审查报告|审查意见|评估结果")
_REVISION_SELF_RE = re.compile(r"修改建议|修订建议|建议修改")
# R4: the contract as an object ("这份合同整体怎么样"), with no clause pointer.
_CONTRACT_SELF_RE = re.compile(r"(这份|这个|该)(合同|协议)|本合同|本协议")
# R1: pure content probes — paired with a clause reference they mean "show me
# what the clause says", which the clause text itself answers.
_CONTENT_PROBE_RE = re.compile(
    r"写的是什么|写了什么|是什么内容|什么意思|啥意思|怎么约定|约定了什么|约定的什么|内容是|怎么写的|说了什么|原文"
)
# Legal-analysis vocabulary keeps a question on the LAW route even when it
# also points at the contract or a clause ("这份合同的违约金条款有效吗" still
# needs statute grounding). Deliberately excludes 风险: "这份合同有哪些风险"
# is answered by the review cards, and sending it to retrieval reproduces the
# risk_type-injection false-citation bug.
_ANALYSIS_RE = re.compile(
    r"有效|无效|合法|违法|违约|赔偿|过高|过低|解除|撤销|生效|失效|担保|抵押|定金|利息|诉讼时效"
)

# GENERIC branch: labor / social-insurance domains are governed by 劳动法 /
# 劳动合同法 / 劳动争议调解仲裁法 / 社保法 — none of which is inside
# civil_code_hybrid (Civil Code articles 1–988 only). Retrieval there can
# only fabricate relevance (baseline G2 cited 第198条 at 0.91 for a
# labor-arbitration question). 劳务合同 stays LAW: it is a civil contract.
_OFF_DOMAIN_RE = re.compile(
    r"劳动合同|劳动关系|劳动仲裁|劳动争议|竞业限制|经济补偿|"
    r"社保|社会保险|公积金|住房公积金|工伤|加班费|加班工资|产假|年休假|年假|"
    r"裁员|辞退|开除|离职补偿|退休|失业保险|养老保险|医疗保险|生育保险"
)


def classify_question(question: str, clauses: list[dict[str, Any]] | None = None) -> str:
    """Route a question to META / CLAUSE / GENERIC / LAW (pure rules, no LLM).

    Priority: META → CLAUSE (review/revision self-reference) → clause-scoped
    content probe → off-domain GENERIC → contract-as-object CLAUSE → LAW.
    Ambiguous questions fall through to LAW on purpose: a wasted retrieval is
    cheaper than a missed statute, and the hard cutoff in retrieve_law_hits
    still guards the citation list downstream.
    """
    q = (question or "").strip()
    if is_meta_question(q):
        return "META"

    # CLAUSE (R2/R3): asking about the review output itself.
    if _REVIEW_SELF_RE.search(q) or _REVISION_SELF_RE.search(q):
        return "CLAUSE"

    clauses = clauses or []
    ref_ids = _referenced_clause_ids(q, clauses)
    if ref_ids:
        # Clause referenced: a pure content probe ("第四条写的是什么") is
        # answered by the clause text; anything analytical keeps retrieval.
        if _CONTENT_PROBE_RE.search(q) and not _ANALYSIS_RE.search(q):
            return "CLAUSE"
        return "LAW"

    # GENERIC: outside the KB's domain by definition.
    if _OFF_DOMAIN_RE.search(q):
        return "GENERIC"

    # CLAUSE (R4): contract-as-object questions with no clause pointer and no
    # legal-analysis vocabulary. Retrieval here would inject top risk_type
    # terms (no referenced clause → pool = ALL cards) and manufacture hits.
    if _CONTRACT_SELF_RE.search(q) and not _ANALYSIS_RE.search(q):
        return "CLAUSE"

    return "LAW"


async def build_qa_context(db: Any, contract_id: int, question: str) -> dict[str, Any]:
    """Assemble the full QA context. Returns {} if the contract does not exist."""
    sources = await fetch_contract_sources(db, contract_id)
    if not sources:
        return {}

    intent = classify_question(question, sources["clauses"])

    # META / CLAUSE / GENERIC never need the statute KB:
    #   META    — the scope-guard system prompt answers greetings/capability;
    #   CLAUSE  — clause text / review cards / revisions are already in context;
    #   GENERIC — outside the KB's coverage; retrieval fabricates relevance.
    # All three return law_empty=True so NO_LAW_NOTE forbids article citations,
    # while the contract context still renders normally.
    if intent in ("META", "CLAUSE", "GENERIC"):
        logger.info(
            f"QA intent={intent} (contract={contract_id}); skipping law retrieval "
            f"for question={question[:40]!r}"
        )
        return {
            **sources,
            "question": question,
            "intent": intent,
            "law_hits": [],
            "citations": [],
            "law_empty": True,
            "confidence_tier": "NA",
        }

    # T2: split compound questions; each fragment is enriched independently so
    # both intents get their own retrieval (single-intent questions return a
    # one-element list and behave exactly as before).
    sub_questions = split_sub_queries(question)
    law_queries = [
        build_law_query(sq, sources["clauses"], sources["cards"]) for sq in sub_questions
    ]
    if len(law_queries) > 1:
        logger.info(f"QA multi-query split (contract={contract_id}): {law_queries}")
    elif law_queries and law_queries[0] != question.strip():
        logger.info(f"QA law query rewritten (contract={contract_id}): {law_queries[0]}")
    # T3: hyde_question carries the RAW question — the HyDE hypothesis must be
    # generated from the user's colloquial phrasing, not from the enriched
    # query (whose injected risk_type terms would bias the hypothesis).
    law_hits = await retrieve_law_hits(law_queries, hyde_question=question)
    return {
        **sources,
        "question": question,
        "intent": intent,
        "law_hits": law_hits,
        "citations": build_citations(law_hits),
        "law_empty": not law_hits,
        "confidence_tier": classify_law_confidence(law_hits),
    }


# ── Rendering with progressive budget reduction ─────────────────────────────

# Each level shrinks per-item char limits and raises the minimum risk level kept.
_REDUCE_LEVELS = [
    {"clause_chars": 500, "card_chars": 250, "evidence_chars": 150, "law_chars": 400, "rev_chars": 200, "min_rank": 0},
    {"clause_chars": 300, "card_chars": 180, "evidence_chars": 120, "law_chars": 300, "rev_chars": 160, "min_rank": 0},
    {"clause_chars": 200, "card_chars": 150, "evidence_chars": 100, "law_chars": 250, "rev_chars": 120, "min_rank": 1},
    {"clause_chars": 120, "card_chars": 100, "evidence_chars": 80, "law_chars": 200, "rev_chars": 100, "min_rank": 2},
]


def _trunc(text: str, limit: int) -> str:
    text = text or ""
    return text if len(text) <= limit else text[:limit] + "…[略]"


def _clause_block(clauses: list[dict[str, Any]], clause_chars: int) -> str:
    lines = []
    for c in clauses:
        title = f"【{c['title']}】" if c.get("title") else ""
        lines.append(f"第{c.get('seq_no', '?')}条{title}：{_trunc(c.get('content', ''), clause_chars)}")
    return "\n".join(lines)


def _review_block(
    cards: list[dict[str, Any]],
    evidence: list[dict[str, Any]],
    clause_titles: dict[str, str],
    card_chars: int,
    evidence_chars: int,
    min_rank: int,
) -> str:
    ev_by_clause: dict[str, list[dict[str, Any]]] = {}
    for e in evidence:  # evidence is pre-sorted by confidence DESC
        ev_by_clause.setdefault(e.get("clause_id", ""), []).append(e)

    lines = []
    for card in cards:
        if _LEVEL_RANK.get(card.get("level", "无"), 0) < min_rank:
            continue
        title = clause_titles.get(card.get("clause_id", ""), "")
        score = card.get("score") or 0.0
        line = (
            f"- 条款{card.get('clause_id', '')}{title} [{card.get('dimension', '')}] "
            f"{card.get('level', '无')}风险(score={score:.2f})：{_trunc(card.get('suggestion', ''), card_chars)}"
        )
        for ev in ev_by_clause.get(card.get("clause_id", ""), [])[:MAX_EVIDENCE_PER_CLAUSE]:
            conf = ev.get("confidence")
            conf_txt = f"{conf:.2f}" if conf is not None else "n/a"
            line += (
                f"\n    依据({ev.get('source_collection', '')}, source_id={ev.get('source_id', '')}, "
                f"置信度{conf_txt})：{_trunc(ev.get('quote', ''), evidence_chars)}"
            )
        lines.append(line)
    return "\n".join(lines)


def _revision_block(revisions: list[dict[str, Any]], rev_chars: int) -> str:
    lines = []
    for r in revisions:
        lines.append(f"- 条款{r.get('clause_id', '')}建议修改为：{_trunc(r.get('after_text', ''), rev_chars)}")
    return "\n".join(lines)


def _law_block(law_hits: list[dict[str, Any]], law_chars: int) -> str:
    lines = []
    for i, hit in enumerate(law_hits, start=1):
        art = hit.get("article_no", "") or "?"
        chapter = hit.get("chapter", "") or ""
        lines.append(f"[{i}] 《中华人民共和国民法典》{art}（{chapter}）：{_trunc(hit.get('content', ''), law_chars)}")
    return "\n".join(lines)


def _render_with(ctx: dict[str, Any], lv: dict[str, int]) -> str:
    clause_titles = {
        c["clause_id"]: (f"【{c['title']}】" if c.get("title") else "")
        for c in ctx.get("clauses", [])
    }
    sections: list[str] = []

    clauses = ctx.get("clauses", [])
    if clauses:
        sections.append("【合同条款】\n" + _clause_block(clauses, lv["clause_chars"]))

    cards = ctx.get("cards", [])
    if cards:
        block = _review_block(
            cards, ctx.get("evidence", []), clause_titles,
            lv["card_chars"], lv["evidence_chars"], lv["min_rank"],
        )
        if block:
            sections.append("【审查结果（多维评审 + 法律依据）】\n" + block)

    revisions = ctx.get("revisions", [])
    if revisions:
        sections.append("【修订建议】\n" + _revision_block(revisions, lv["rev_chars"]))

    law_hits = ctx.get("law_hits", [])
    if law_hits:
        sections.append("【实时检索到的法律依据（引用时使用编号）】\n" + _law_block(law_hits, lv["law_chars"]))

    return "\n\n".join(sections)


def render_context(ctx: dict[str, Any], budget: int = QA_TOKEN_BUDGET) -> str:
    """Render numbered context within the token budget via progressive reduction.

    Reduction order: shrink law/quote char limits → drop 无/低-level cards →
    shrink clause content. The strictest level is used as a last resort.
    """
    for lv in _REDUCE_LEVELS:
        text = _render_with(ctx, lv)
        if estimate_tokens(text) <= budget:
            return text
    return _render_with(ctx, _REDUCE_LEVELS[-1])
