"""
QA answer service — streams grounded answers about a reviewed contract.

Hard rules enforced here:
  1. Grounded citations — context entries are numbered [1..n]; the LLM may only
     cite numbers that actually exist in the context. Citations persisted with
     the answer are generated by the backend from retrieval results.
  2. No fabrication — when live retrieval returns nothing, the prompt explicitly
     forbids citing any article number.
  3. Scope guard — context only contains data of the current contract
     (enforced upstream in context_builder SQL filters).

Note: the QA LLM is constructed locally (Q-1) instead of reusing the lru_cache
instance in core/llm.py, so QA-specific temperature/max_tokens never pollute
the review pipeline.
"""
from __future__ import annotations

import json
import logging
from collections.abc import AsyncIterator
from typing import Any

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

from backend.agents.contract_qa.context_builder import build_qa_context, render_context
from backend.config import get_settings

logger = logging.getLogger(__name__)

QA_LLM_MAX_TOKENS = 2048
QA_TEMPERATURE = 0.2
HISTORY_TURNS = 6  # NOTE: counts MESSAGES (≈3 turns), not turn pairs

# ── Rolling summary (long-term memory) ──────────────────────
# Triggered once a session accumulates ≈10 turns of completed messages;
# the summary is injected into the pinned SystemMessage, complementing the
# recent-message sliding window (window controls tokens, summary keeps semantics).
SUMMARY_TRIGGER_MESSAGES = 20
SUMMARY_BATCH_LIMIT = 40      # max messages summarized in one call
SUMMARY_QUOTE_CHARS = 300     # per-message truncation when building the dialogue
SUMMARY_MAX_TOKENS = 512
SUMMARY_STORE_CHARS = 2000    # hard cap for the persisted summary

SYSTEM_PROMPT = (
    "你是「合同审查助手」的智能问答模块，服务对象是刚完成合同审查的用户。\n"
    "你只能依据下方提供的【上下文】回答问题，并遵守以下硬性规则：\n"
    "1. 范围守卫：你只回答与本合同相关的问题（条款内容、审查结果、修订建议、相关法律依据）。"
    "与本合同无关的问题（闲聊、写作、其他合同事务），请礼貌说明你只负责本合同的审查问答。\n"
    "2. 引用溯源：引用法律依据时必须使用上下文中出现的编号（如 [1]、[2]），"
    "只能引用上下文中真实存在的编号，严禁编造任何法律条文或编号。\n"
    "3. 诚实原则：上下文中没有的信息，如实说明「未在审查结果或检索结果中找到」，不要猜测或虚构。\n"
    "4. 使用中文回答，简明扼要；涉及风险结论时提醒用户最终以执业律师意见为准。"
)

NO_LAW_NOTE = (
    "\n注意：本次未检索到直接法律依据。回答中不得出现任何法条编号引用（如 [1]），"
    "如用户追问法律依据，请如实告知暂未检索到相关条文。"
)

WEAK_CONFIDENCE_NOTE = (
    "\n注意：本次检索到的法律依据置信度较低。回答时请弱化肯定语气，"
    "明确标注「依据较弱，建议结合具体案情并咨询执业律师」；"
    "不得将低置信依据当作确定结论。"
)


def _build_qa_llm(max_tokens: int = QA_LLM_MAX_TOKENS, temperature: float = QA_TEMPERATURE) -> ChatOpenAI:
    """QA-dedicated LLM instance — do NOT reuse core.llm._cached_llm (Q-1).

    ``temperature`` defaults to QA_TEMPERATURE for answer generation; callers
    may override for retrieval-auxiliary calls (the T3 HyDE hypothesis uses
    0.0 so the same question always produces the same hypothesis).
    """
    settings = get_settings()
    return ChatOpenAI(
        base_url=settings.llm_api_base,
        api_key=settings.llm_api_key,
        model=settings.llm_model,
        temperature=temperature,
        max_tokens=max_tokens,
    )


async def _load_history(db: Any, session_id: int, before_message_id: int) -> list[dict[str, str]]:
    """Most recent completed messages (oldest → newest)."""
    rows = await db.fetch(
        "SELECT role, content FROM contract_qa_messages "
        "WHERE session_id = $1 AND id < $2 AND status = 'completed' AND content <> '' "
        "ORDER BY id DESC LIMIT $3",
        session_id, before_message_id, HISTORY_TURNS,
    )
    return [{"role": r["role"], "content": r["content"]} for r in reversed(rows)]


def build_prompt_messages(
    ctx: dict[str, Any],
    history: list[dict[str, str]],
    question: str,
    summary: str = "",
) -> list[BaseMessage]:
    """Compose [system(+summary+context), history..., human(question)].

    ``summary`` is the rolling session summary (long-term memory); it is
    injected into the pinned SystemMessage so it always stays at position 0.
    """
    review = ctx.get("review", {}) or {}
    meta_bits = []
    if review.get("original_filename"):
        meta_bits.append(f"合同文件：{review['original_filename']}")
    if review.get("contract_type"):
        meta_bits.append(f"合同类型：{review['contract_type']}")
    meta = ("【合同信息】" + "；".join(meta_bits)) if meta_bits else ""

    system_text = SYSTEM_PROMPT
    if meta:
        system_text += "\n\n" + meta
    if ctx.get("law_empty"):
        system_text += NO_LAW_NOTE
    elif ctx.get("confidence_tier") == "WEAK":
        system_text += WEAK_CONFIDENCE_NOTE
    if summary and summary.strip():
        system_text += "\n\n【历史对话摘要】\n" + summary.strip()

    context_text = render_context(ctx)
    if context_text:
        system_text += "\n\n【上下文】\n" + context_text

    messages: list[BaseMessage] = [SystemMessage(content=system_text)]
    for h in history:
        if h["role"] == "user":
            messages.append(HumanMessage(content=h["content"]))
        else:
            messages.append(AIMessage(content=h["content"]))
    messages.append(HumanMessage(content=question))
    return messages


async def _finalize(db: Any, message_id: int, content: str, citations: list[dict[str, Any]]) -> None:
    await db.execute(
        "UPDATE contract_qa_messages SET content = $2, citations = $3, status = 'completed' "
        "WHERE id = $1",
        message_id, content, json.dumps(citations, ensure_ascii=False),
    )


async def _mark_failed(db: Any, message_id: int, error: str) -> None:
    try:
        await db.execute(
            "UPDATE contract_qa_messages SET status = 'failed', error_message = $2 WHERE id = $1",
            message_id, error[:500],
        )
    except Exception:
        logger.exception("Failed to mark QA message as failed")


# ── Rolling summary (long-term memory) ────────────────────────────────────

def needs_summary(completed_count: int) -> bool:
    """True when a session has enough completed messages to deserve a summary."""
    return completed_count >= SUMMARY_TRIGGER_MESSAGES


def _trunc_text(text: str | None, limit: int) -> str:
    text = text or ""
    return text if len(text) <= limit else text[:limit] + "…"


def format_summary_prompt(old_summary: str, dialogue: str) -> list[BaseMessage]:
    """Messages for the rolling-summary LLM call.

    Built with plain concatenation — no ``.format()`` placeholders to mismatch.
    Keeps what the reference material calls the cross-window essentials:
    clauses/risk points the user focused on, confirmed conclusions, open follow-ups.
    """
    old = old_summary.strip() if old_summary and old_summary.strip() else "（暂无）"
    return [
        SystemMessage(content=(
            "你是对话记录员，负责把「合同审查助手」与用户的问答历史压缩成简明摘要。"
            "摘要必须保留：1) 用户关注过的条款号与风险点；2) 已确认的结论；"
            "3) 用户尚未解决的追问。不超过300字，直接输出摘要正文，不要输出任何解释。"
        )),
        HumanMessage(content=(
            f"已有摘要：\n{old}\n\n新增对话：\n{dialogue}\n\n请输出更新后的完整摘要。"
        )),
    ]


async def _maybe_summarize(db: Any, session_id: int) -> None:
    """Rolling summary: compress old messages once the session grows past the trigger.

    The recent ``HISTORY_TURNS`` messages stay verbatim in the sliding window;
    everything newer than ``summarized_until`` and older than that window is
    folded into ``sessions.summary`` (old summary rolled forward, never lost).

    Best-effort by contract — callers must wrap this in try/except so a
    summary failure never blocks the answer path.
    """
    count = await db.fetchval(
        "SELECT COUNT(*) FROM contract_qa_messages "
        "WHERE session_id = $1 AND status = 'completed' AND content <> ''",
        session_id,
    )
    if not needs_summary(int(count or 0)):
        return

    sess = await db.fetchrow(
        "SELECT summary, summarized_until FROM contract_qa_sessions WHERE id = $1",
        session_id,
    )
    if not sess:
        return
    watermark = sess["summarized_until"] or 0

    # Completed messages after the watermark, excluding the recent window
    # (kept verbatim). DESC + OFFSET skips the window; cap the batch size.
    rows = await db.fetch(
        "SELECT id, role, content FROM contract_qa_messages "
        "WHERE session_id = $1 AND status = 'completed' AND content <> '' AND id > $2 "
        "ORDER BY id DESC OFFSET $3 LIMIT $4",
        session_id, watermark, HISTORY_TURNS, SUMMARY_BATCH_LIMIT,
    )
    if not rows:
        return

    newest = max(r["id"] for r in rows)
    dialogue = "\n".join(
        f"{'用户' if r['role'] == 'user' else '助手'}：{_trunc_text(r['content'], SUMMARY_QUOTE_CHARS)}"
        for r in reversed(rows)  # chronological order
    )

    llm = _build_qa_llm(max_tokens=SUMMARY_MAX_TOKENS)
    result = await llm.ainvoke(format_summary_prompt(sess["summary"] or "", dialogue))
    piece = result.content if isinstance(result.content, str) else str(result.content)
    new_summary = piece.strip()
    if not new_summary:
        return

    await db.execute(
        "UPDATE contract_qa_sessions SET summary = $2, summarized_until = $3 WHERE id = $1",
        session_id, new_summary[:SUMMARY_STORE_CHARS], newest,
    )
    logger.info(f"QA session {session_id} summary updated (watermark -> {newest})")


async def stream_answer(message_id: int, question: str) -> AsyncIterator[dict[str, Any]]:
    """Stream a grounded answer for the pending assistant message `message_id`.

    Yields event dicts:
      {"type": "citations", "items": [...]}   — before the first delta
      {"type": "delta", "text": "..."}        — incremental answer text
      {"type": "done"}                        — answer completed & persisted
      {"type": "error", "message": "..."}     — degraded, message marked failed
    """
    import asyncpg

    db_url = get_settings().database_url
    db = await asyncpg.connect(db_url)
    try:
        # ── Locate message → session → contract (ownership re-checked by caller) ──
        msg = await db.fetchrow(
            "SELECT m.session_id, s.contract_id FROM contract_qa_messages m "
            "JOIN contract_qa_sessions s ON s.id = m.session_id WHERE m.id = $1",
            message_id,
        )
        if not msg:
            yield {"type": "error", "message": "Message not found"}
            return

        session_id = msg["session_id"]
        contract_id = msg["contract_id"]

        # ── Assemble context (three sources + live retrieval) ──
        ctx = await build_qa_context(db, contract_id, question)
        if not ctx:
            await _mark_failed(db, message_id, "contract not found")
            yield {"type": "error", "message": "Contract not found"}
            return

        citations = ctx["citations"]
        yield {"type": "citations", "items": citations}

        history = await _load_history(db, session_id, message_id)
        sess_row = await db.fetchrow(
            "SELECT summary FROM contract_qa_sessions WHERE id = $1", session_id
        )
        summary = (sess_row["summary"] or "") if sess_row else ""
        messages = build_prompt_messages(ctx, history, question, summary)

        # ── Stream generation ──
        llm = _build_qa_llm()
        full_text = ""
        try:
            async for chunk in llm.astream(messages):
                piece = chunk.content if isinstance(chunk.content, str) else str(chunk.content)
                if piece:
                    full_text += piece
                    yield {"type": "delta", "text": piece}
        except Exception as e:
            logger.exception(f"QA LLM streaming failed for message {message_id}")
            await _mark_failed(db, message_id, str(e))
            yield {"type": "error", "message": f"Answer generation failed: {e}"}
            return

        if not full_text.strip():
            full_text = "抱歉，本次未能生成有效回答，请重试或换一种问法。"

        await _finalize(db, message_id, full_text, citations)
        await db.execute(
            "UPDATE contract_qa_sessions SET updated_at = NOW() WHERE id = $1", session_id
        )

        # Best-effort long-term memory: never blocks or fails the answer path.
        try:
            await _maybe_summarize(db, session_id)
        except Exception:
            logger.exception(f"QA summary update failed for session {session_id} (non-fatal)")

        yield {"type": "done"}
    except Exception as e:
        logger.exception(f"QA stream_answer failed for message {message_id}")
        await _mark_failed(db, message_id, str(e))
        yield {"type": "error", "message": str(e)}
    finally:
        await db.close()
